steps:
  # Step 1: Build the container image.
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}', '.']

  # Step 2: Push the image.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}']

  # Step 3: Deploy to Cloud Run.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud run deploy '${_SERVICE_NAME}' \
        --image '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}' \
        --region '${_GCP_REGION}' \
        --platform 'managed' \
        --allow-unauthenticated \
        --project '${PROJECT_ID}' \
        --update-secrets=GEMINI_API_KEY=gemini-api-key:latest \
        --set-env-vars="^#^GCP_PROJECT_ID=${PROJECT_ID}#GCP_REGION=${_GCP_REGION}#GCP_SOURCE_BUCKET_NAME=${_GCP_SOURCE_BUCKET_NAME}#FIRESTORE_SERVICES_COLLECTION=services#CORS_ORIGINS=http://localhost:5173,https://api-architect.vercel.app"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: 'api-architect-core'
  _GCP_REGION: 'us-central1'
  _REPOSITORY: 'api-architect-repo'
  _GCP_SOURCE_BUCKET_NAME: 'api-architect-source-code'

images:
  - '${_GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
